#!/usr/bin/env python3
# ------------------------------------------------------------------------------
#
# Copyright (c) 2023 Pixar. All rights reserved.
#
# The information in this file (the "Software") is provided for the exclusive
# use of the software licensees of Pixar ("Licensees").  Licensees have the
# right to incorporate the Software into other products for use by other
# authorized software licensees of Pixar, without fee. Except as expressly
# permitted herein, the Software may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior written
# permission of Pixar.
#
# The copyright notices in the Software and this entire statement, including the
# above license grant, this restriction and the following disclaimer, must be
# included in all copies of the Software, in whole or in part, and all permitted
# derivative works of the Software, unless such copies or derivative works are
# solely in the form of machine-executable object code generated by a source
# language processor.
#
# PIXAR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL PIXAR BE
# LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.  IN NO CASE WILL
# PIXAR'S TOTAL LIABILITY FOR ALL DAMAGES ARISING OUT OF OR IN CONNECTION WITH
# THE USE OR PERFORMANCE OF THIS SOFTWARE EXCEED $50.
#
# Pixar
# 1200 Park Ave
# Emeryville CA 94608
#
# ------------------------------------------------------------------------------

#
# Generate Tractor JSON job definitions from
# alfred-style Tcl-based job scripts.
#
# dml, 09/2023
#
#
# The original Tractor/Alfred jobs were written to be parsed by a
# "readily available" Tcl (tclsh) interpreter. As Python became
# more standard for full app development, the Tractor job submission
# scheme required both interpreters. To simplify product deployment,
# Tractor (2.0) shipped with a full bundled python distribution (2.7.2)
# that included an embedded Tcl interpreter (c++ module) callable from
# python scripts.
#
# This script is a new pure-python "alf2json" module that addresses
# the problem of providing a job submission/parsing solution that
# can be run in stock Python distributions without the need to build
# and distribute the compiled Tcl module for each platform variant.
#
# This python implementation essentially treats Tractor jobs as
# "structured data" only, not as full tclsh scripts (for example, no
# inline tcl execution or even variable substitution are allowed).
# The code is really in two parts:
#  - A simplistic tokenizer, aware of a limited Tcl-like grammar.
#  - Job-specific handling of the tokenizer results to produce a
#    JSON job representation. It includes logic to handle various
#    anachronistic job script details for backward compatibility.
#
# This is a line-oriented parser, handling nested subtask and cmd
# blocks with a simple depth tracker and NO RECURSION. It builds
# stock python dicts and lists directly without requiring any
# intermediate python classes for Job, Task, Cmd, etc. The python
# dict/list hierarchy is serialized to JSON.
#
# The approach is to read the job file one line at a time.
# Actionable lines will have a Tcl-like expression form:
#
#   jobElement -optionName valueString [more opt-value pairs...]
#
# In the old Tcl implementation, each job element was implemented
# as a standard Tcl operator: Job, Task, RemoteCmd, Cmd, Assign.
# Each operator handled its arguments, delivered the Tcl interpreter,
# in its own "custom" fashion (in the tcl code for the operator).
#
# In this implementation we're treating the script as just
# structured data instead, so the given job element keywords
# dictate the processing rules applied to subsequent tokens,
# however most are indeed key-value pairs and are just placed
# into each element's associated python dict directly.
#
# There is a longstanding Task and Cmd syntax anachronism where they
# both have one required parameter that is not given as a key-value
# pair, just the valueString is given, with the optionName implied.
#
# Recall that in Tcl, double-quotes and curly-braces are both
# used as string delimiters, and that literal strings can contain
# newlines. Some std Tcl operators like [lindex] examine strings
# for nested string subsyntax and create Tcl lists from them.
# Depending on context in job scripts, curly-brace strings are
# treated as simple strings, or sometimes lists, and also to
# denote multi-line blocks of subtasks or commands. Those blocks
# were recursively parsed in Tcl for more Task and Cmd operator
# statements. Here we handle those particular multi-line blocks
# line by line and simply track nested scope depth as we go.
#
# These subtask and cmd blocks (specifically) can be handled
# in a line-by-line fashion without recursion because alfred job
# scripts always present the task hierarchy tree in a strictly
# depth-first nesting order. When a block is found, state from
# the current Task is pushed on a simple stack and items from
# inside the block are inserted into the topmost task.
# Updates return to the prior task dict when the block ends.
#
# == Other notes ==
#
# Preview and chaser commands...
# See the trSiteOpenPreviewLink() comments in the site modifiable
# trSiteDashboardFunctions.js config file. Format like
#    Task -preview { cmdline }  or -chaser { cmdline }
# These strings are messages to the Tractor javascript code running
# in the dashboard (browser). The job database expects these directive
# strings to be converted to json "argv" style tokenized lists, though
# they can be interpreted differently by the site plug-in.
#


from __future__ import print_function
import sys
import os
import json
import time
import socket
import getpass
import os.path
from io import StringIO

# Hack to support both Python 2 and 3
if str == type(u''):
    unicode = str

## ===== ##

def usage():
    print("debugging usage:\n", sys.argv[0], "[--pretty --debug --altdict] jobfile.alf", file=sys.stderr)
    sys.exit(1)

## ===== ##

s_defaultParams = {
    "Job": {
        "jid": 0,  # real jid assigned by engine
        "title": "",
        'afterjids': [],
        'aftertime': 0,
        "atleast": 1,  # prefer minslots
        "atmost": 1,   # prefer maxslots
        'etalevel': '',
        "cleanup": '',
        "cids": [], # summary of cmd-ids on a task
        "cmds": [],
        'comment': '',
        'crews': [],
        'dirmaps': '',  # captured as str, becomes []
        "envkey": [],
        'editpolicy': '',
        "init": '',
        "maxhosts": 0,
        "maxactive": 0,
        "maxslots": 0,
        "minslots": 0,
        "metadata": '',
        "owner": '',
        'paused': 0,
        "pbias": 0.0,
        "priority": 1.0,
        'projects': [],
        "service": '',
        "serialsubtasks": 0,
        "spoolcwd": '',
        "spoolhost": '',
        "spoolfile": '',
        "subtasks": [],
        "tags": '',
        "tid": None,
        'tier': '',
        "postscript": '',
        "whendone": '',
        "whenerror": '',
    },

    "Task":  {
        "tid": None,
        "title": "",
        "serialsubtasks": 0,
        "subtasks": [],
        "cmds": [],
        "cids": [], # summary of cmd-ids on a task
        "service": '',
        "envkey": [],
        "tags": '',
        "atleast": 1,  # prefer minslots
        "atmost": 1,   # prefer maxslots
        "minslots": 0,
        "maxslots": 0,
        "maxhosts": 0,
        "metadata": '',
        "refersto": '',
        "id": '',
        "preview": [],
        "chaser": [],
        "cleanup": '',
        "resumeblock": 0,
        "ants": [], # antecedents, from 'Instance tttt'
    },

    "Cmd": {
        "cid": None,
        "argv": [],
        "type": '',
        "msg": '',
        "retryrc": [],
        "minrunsecs": 0.0,
        "maxrunsecs": 0.0,
        "resumepin": 0,
        "resumewhile": [],
        "service": '',
        "envkey": [],
        "tags": '',
        "atleast": 1,  # prefer minslots
        "atmost": 1,   # prefer maxslots
        "minslots": 0,
        "maxslots": 0,
        "maxhosts": 0,
        "samehost": 1,
        "metadata": '',
        "refersto": '',
        "id": '',
        "expand": 0,
        "when": '',
    }
}

## ===== ##

class TrAlfParseError(Exception):
    pass

## ===== ##


def ParseAlfJob(options, jobfile, jobtext=None, openedfile=None):
    '''Read a Tractor "alfred-format" job script
       and convert it to a JSON dict hierarchy
       as expected by the Tractor2 job database.
    '''

    try:
        if not getattr(options, 'jobfile', ''):
            options.jobfile = jobfile  # a label in this case

        alfParser = AlfJobParser(options)

        if jobtext:
            # Received an in-memory job as a text block.
            jtxt = StringIO(unicode(jobtext))
            return alfParser.xlateAlfToJSON(jtxt)

        elif openedfile:
            return alfParser.xlateAlfToJSON(openedfile)

        else:
            # Read the job file from disk.
            # Open the file within an auto-close context.
            with open(jobfile, "r") as jf:
                return alfParser.xlateAlfToJSON(jf)

    except Exception as err:
        msg = str(err)
        if getattr(options, "IsModuleTest", False):
            if options.loglevel >= 5:
                import traceback
                msg += "\n" + traceback.format_exc()

            print("Error - ParseAlfJob:", msg, file=sys.stderr)
            return None
        else:
            raise err

## ===== ##
def ParseAlfJobAsString(jobtext, loglevel=1):
    '''Simplified entry point for job authoring API to use.
       Parse an in-memory alf job text buffer.
    '''
    if not jobtext:
        return ''
    else:
        class MinimalOptions(object):
            pass
        opts = MinimalOptions()
        opts.loglevel = loglevel

        return AlfJobParser(opts).xlateAlfToJSON(
                    StringIO(unicode(jobtext))
                )

## ===== ##

class AlfJobParser(object):
    '''Read an alfred-style job definition from the specified file,
       and parse it as "job data" (but not executable Tcl).
       Build an intermediate Python hierarchy of dicts and lists
       representing the Task/Cmd structure, then serialize that
       as JSON in the slightly awkward form expected by Tractor2.
       Parsing line-by-line to help minimize intermediate copies
       of large job scripts.
    '''

    def __init__(self, options):
        # Inbound options are expected to be an object similar to those
        # created by the optparse or argparse modules. But really it's
        # just an object carrying attributes that can be queried.

        self.options = options

        #  "2.0" is Tractor2 compat, "3.0" is a simpler layout and escaping
        self.options.jsonAPI = getattr(options, "jobspec", "2.0")

        self.options.jobowner    = getattr(options, "user", getpass.getuser())
        self.options.jobfile     = getattr(options, "jobfile", "<scripted>")
        self.options.loglevel    = getattr(options, "loglevel", 1)
        self.options.priority    = getattr(options, "priority", 1.0)
        self.options.paused      = getattr(options, "paused", 0)
        self.options.cleanupSvc  = getattr(options, "remoteclean", "PixarRender")
        self.options.jobcwd      = getattr(options, "jobcwd", os.getcwd().replace("\\", "/"))
        self.options.spooltime   = getattr(options, "spooltime", time.time())
        self.options.jsonformat  = getattr(options, "jsonformat", (None, (',', ':')))
        self.options.spoolerHost = getattr(options, "hname", '')
        self.options.expandctx   = getattr(options, "expandctx", None)
        self.options.envkey      = getattr(options, "envkey", [])
        self.options.strict      = getattr(options, "strict", False)

        if not self.options.spoolerHost:
            self.options.spoolerHost = socket.gethostname().split('.')[0]

        if self.options.jobfile and list == type(self.options.jobfile):
            self.options.jobfile = self.options.jobfile[0] + "..."

        # parser state / tracking
        self.ntid = 0
        self.ncid = 0
        self.context = None
        self.cmdScope = 'C'  # of C, D, P
        self.taskStack = []
        self.jobsrc = None
        self.linenum = 0
        self.linebuf = StringIO() # reused line buffer


    def xlateAlfToJSON(self, jobsrc):
        '''Parse the inbound lines to construct a nested hierarchy
           of python dicts representing the job's task tree.
           Then serialize the python data to outbound JSON.
        '''

        ctx = "Job" if not self.options.expandctx else "Expand"

        self.jobsrc = jobsrc

        theJob = self.initJobStatement()  # skeleton job dict

        theJob = self.handleJobStatements(ctx, theJob)

        # done reading file!
        theJob = self.finalizeJobForJSON(theJob)

        return self.generateJSON(theJob)


    def handleJobStatements(self, ctx, theJob, curTask=None):
        '''Evaluate job script objects and their parameters,
           create Python objects of each type in a nested tree.'''

        # NOTE: theJob is initialized in initJobStatement
        self.CTX(ctx)
        while True:
            self.dbg("MAINLOOP")

            # Read next line from the job script, buffer it.
            if not self.refillLineBuffer():
                self.dbg("[[[ EOF - END OF JOB SCRIPT ]]]")
                break   # reached end of input (EOF)

            thing = self.findOneTclToken()
            self.dbg("new thing:", repr(thing))
            if not thing:
                continue  # odd empty buffer, get another

            elif thing == "_BlockEnd_":
                # This line begins with a close-brace, marking the end of
                # a subtask or cmd block. That block parameter value is now
                # complete, so tidy the state and then continue scanning
                # for additional Task parameters.
                curTask = self.handleBlockEnd(curTask)

            elif "Instance" == thing:
                # non-tree ref to a blocking task
                self.handleInstanceStatement()
                # now no active task still capturing params
                curTask = None

            elif not self.contextOK(thing, theJob):
                raise TrAlfParseError("unexpected '%s' in %s context, line %d" % (thing,self.CTX(),self.linenum))

            elif "Job" == thing:
                # Update the supplied Job parameters.
                # The basic top-level Job dict was created above 
                # by initJobStatement().
                curTask = self.addTaskParams(theJob)

            elif "Task" == thing:
                curTask = self.handleTaskStatement()

            elif thing in ("RemoteCmd", "Cmd"):
                # expect:
                #   RemoteCmd -service sss -x y {echo "the args" today}
                #         Cmd -x y {run this on submitting host}

                # collect cmd parameters, then add (one) new cmd to task
                self.handleCmdStatement(thing, curTask, theJob)

            elif thing == "Assign":
                self.handleAssignStatement()

            else:
                raise TrAlfParseError("unrecognized job script statement/node type '%s' line %d" % (thing, self.linenum))

        return theJob


    def initJobStatement(self):
        # Create the Job top level.
        # Jobs are just specialized Tasks with extra attributes.
        #
        # NOTE: dict items defined here will be sent in the 
        #       outbound JSON if they differ from the defaults.

        t = int(self.options.spooltime)

        job = {
            "jid": 0,  # real jid set by tractor-engine
            "owner":     self.options.jobowner,
            "spoolhost": self.options.spoolerHost,
            "spooltime": t,
            "spooldate": time.strftime("%Y-%m-%d %H:%M:%S %Z", time.localtime(t)),
            "spoolfile": self.options.jobfile,
            "spoolcwd":  self.options.jobcwd,
            "tid": 0,  # by convention for the job "task"
            "commands": [],
            "subtasks": [],
        }
        optional = {
            ("title", "jtitle"),
            "paused",
            "priority",
            "crews",
            "projects",
            "envkey",
            ("afterjids", "afterjid"),
            "aftertime",
            "maxactive",
            "tags",
            "tier",
            "comment",
            "metadata",
        }
        self.chkOptionals(optional, self.options, job)

        # return the job dict
        return job


    def chkOptionals(self, optional, inopts, job):
        for name in optional:
            if tuple == type(name):
                oname = name[1]
                name = name[0]
            else:
                oname = name
            
            x = getattr(inopts, oname, None)
            if x != None:
                dflt = s_defaultParams["Job"][name]
                kind = type(dflt)
                try:
                    if name == "aftertime":
                        x = self.chkDelayTime(x)
                    elif kind == int:
                        x = int(x)
                    elif kind == list:
                        x = self.chkIsList(x)
                    else:
                        x = str(x)
                        
                    if x != dflt:
                        job[name] = x
                except:
                    print("Error: cannot set job option '%s' to '%s'" % (name,x), file=sys.stderr)


    def handleTaskStatement(self):
        # expect:
        #
        #  Task {some title} [options] -subtasks {...} -cmds {...}
        #
        # Note the missing implicit "-title" preceeding title!
        # So we'll add an explicit "-title" keyword, so that
        # regular key-value processing can proceed below.

        # Increment the global task id/count.
        # Then negate the tid and save that in the dict
        # as an indicator that the task has been created
        # but not yet attached to the job graph.
        tid = self.ntid + 1
        self.ntid = tid

        curTask = {  # a new Task parameter dictionary
            "title": "",
            "commands": [],
            "subtasks": [],
        }
        curTask['tid'] = -tid
        self.dbg("created <<Task>>", curTask['tid'])

        return self.addTaskParams(curTask)


    def mkNewCmd(self):
        '''Create a new dictionary of (Remote)Cmd parameters'''
        self.ncid += 1  # incr global cmd id/count
        cmd = {
            "cid": self.ncid,
            "argv": [],
            "type": '',
        }
        self.dbg("created CID(%d)" % self.ncid)
        return cmd


    def handleCmdStatement(self, mode, curTask, curJob):
        '''Populate a new cmd dict with scanned parameters.'''
        #
        # Must handle ancient RemoteCmd anachronism re: argv,
        # namely that the argv string can occur anywhere
        # among params, but has no "-argv" keyword!
        #
        # like: RemoteCmd -service "linux_2XL" -atmost 1 "sleep 4"
        #   or: RemoteCmd {my command xyz} -service linux_2XL
        #
        implicit = "argv"
        cmdTag = ''

        cmd = self.mkNewCmd()

        while True:
            key, value = self.gatherNextParamPair(implicit)
            if not key:
                # reached EOL, cmd parameters complete
                break
            elif key == "_BlockEnd_":
                # Reached end of parameters, and also this
                # command was the last one in the -cmds block,
                # push that back on the read stream for the 
                # task-level scan to find it.
                self.rewind1("cmdblk")
                break
            elif not value:
                # skip, param has default value
                continue
            else:
                # got a valid RemoteCmd key,
                # and the value is different than the default
                self.dbg("  Adding", key, '=', value, "to cmd cid:", cmd['cid'])
                cmd[key] = value

                if implicit == key:
                    # found a value for the implicit key, so return
                    # to requiring proper key-value pairs only
                    implicit = None

        # reached end of cmd params,
        # tidy various details
        if cmd['argv']:
            cmdTag = self.normalizeExeFilename(cmd)
        else:
            raise TrAlfParseError("missing launch executable in -cmds, line %d" % self.linenum)

        # The command "type" defines where and when it runs over the course
        # of the job. Where is either local or remote (workstation or farm)
        # and when is either during the main body of the job or after
        # processing is complete (at both task and job levels). The "when"
        # is usually determined by the parameter scope in which the cmd is
        # found, -cmds {} or -cleanup {} blocks, plus some other case. 
        # See addTaskParameters() where the scope is known and stored into
        # self.cmdScope.
        #
        # Command type & scope, such as RC or RD or LPD or RCX
        #  First letter:
        #    L or R  - local or remote command (Cmd vs RemoteCmd)
        #  Second letter:
        #    C - regular command
        #    D - a cleanup or "deleting" command
        #    P - job postscript, runs at job end
        #  Third letter:
        #    X - after C, cmd will "expand" to other tasks
        #    D - after P, runs when the job is Done
        #    E - after P, runs when the job had Errors
        #
        # Local commands must run on the submitting workstation
        # (an Alfred concept that is increasingly outdated).
        # If needed, the engine creates local commands by setting
        # the command service key to the workstation hostname,
        # as seen by the engine host - similar to:
        #        if mode == "Cmd" and not cmd.get('service'):
        #            cmd["service"] = self.spoolerHost
        #
        # Also, to support really old RfM format jobs, if the service
        # prefix is "local:" then the command is coerced into a local
        # cmd if it isn't already, and the service key is dropped but
        # the suffix is retained in the tags for limit counting.

        cmdModeBase = {
            "Cmd":       'L',  # Local
            "RemoteCmd": 'R',  # Remote
        }
        cmdType = cmdModeBase[mode]

        svc = cmd.get('service')
        if svc and svc.startswith("local:"):
            cmdType = 'L'
            cmdTag = svc[6:] + ' ' + cmdTag
            del cmd['service']
            svc = None

        if cmdType == 'L' and self.cmdScope == 'D':
            svc = self.options.cleanupSvc
            if svc:
                cmdType = 'R'
                cmd['service'] = svc
            
        if mode=="RemoteCmd" and not svc and not self.options.expandctx and \
            not cmd.get('refersto') and not curJob.get('service'):
            # This exception is spurious when the Job-level -service option
            # is given after all cmds since this parser is line-by-line and
            # hasn't see the (correct) job-level service yet. Usually it is
            # emitted at the top of the alfscript by job authoring toosl.
            raise TrAlfParseError("Job syntax error, no RemoteCmd -service/-refersto given or inherited, line %d" % self.linenum)

        cmdType += self.cmdScope  # like RC or RD or RP

        if cmd.get("expand", 0):
            cmdType += 'X'

        when = cmd.get("when",'')
        if when:
            del cmd["when"]  # don't emit in JSON
            if self.cmdScope != 'P':  # postscripts only
                raise TrAlfParseError("Command -when is only valid inside the Job -postscript block")
            else:
                if when == "done":
                    cmdType += 'D'   # like RPD
                elif when == "error":
                    cmdType += 'E'   # like RPE
                else:
                    raise TrAlfParseError("Unknown command -when value: %s" % when)

        cmd["type"] = cmdType

        # now tags and argv/cmdTag are both in hand, so finalize limit tags
        cmd["tags"] = self.reformatLimitTags(cmd.get("tags",'') + ' ' + cmdTag)

        self.updateSlotCounts(cmd)
        if "maxslots" in cmd and 0 < cmd["maxslots"]:
            cmd["maxhosts"] = 1  # cmd only, 2.0 compat

        #
        # Now the Cmd is complete!
        # Attach it to its enclosing task.
        #
        self.addCmdToTask(cmd, curTask)


    def addCmdToTask(self, cmd, curTask):
        self.dbg("ADDING cmd", cmd['cid'], "to task", curTask['tid'], "nc:", len(curTask['commands']))
        curTask['commands'].append(cmd)
        if 'cids' not in curTask:
            curTask['cids'] = [cmd['cid']]
        else:
            curTask['cids'].append(cmd['cid'])


    def handleInstanceStatement(self):
        # A simple reference some other task as a blocking
        # requirement in a not-strictly-tree way. Can appear 
        # in a subtask group, like "Task". These references
        # (to the TITLE(!) of the other task) are stored in
        # a separate "antecedents" list on the blocked
        # (parent/successor) task.

        if self.CTX() != "Task" or not self.taskStack:
            raise TrAlfParseError("'Instance' only allowed in subtask context, line %d" % self.linenum)

        taskref = self.findOneTclToken()

        pt = self.taskStack[-1] # parent on stack
        if "ants" not in pt:
            pt["ants"] = []

        pt["ants"].append(taskref)

        self.dbg("ADDING Instance ref <", taskref, "> to task", pt['tid'])


    def handleAssignStatement(self):
        '''The Assign operator is unsupported here,
           but consume the parameters.
        '''
        self.dbg("Assign loop ...")
        while True:
            key = self.findOneTclToken()
            if not key or key == "_BlockEnd_":
                # End of parsing inside -init block.
                break
            value = self.findOneTclToken()
            self.dbg("(skip) Assign", key, value)

    def handleBlockEnd(self, curTask):
        # found _BlockEnd_ on a new line or inline after cmds or subtasks
        if "Cmd" == self.CTX():
            # This was the final Cmd tastement in the task's -cmds block,
            # so resume finding any addition task-level parameters ...
            self.dbg("end CMD block in tid:", curTask['tid'] if curTask else "<<none>>")
            self.CTX("Task")

        elif "Task" == self.CTX():
            if curTask:
                # Stow the final subtask in the block if no eol prior.
                self.chkAttachTaskToParent(curTask)

            # then return the param parsing scope to the parent
            curTask = self.taskStack.pop()
            self.dbg("POP stk =", len(self.taskStack), "task now:", curTask['tid'])
            self.dbg("  after block, task =", curTask['tid'])

        elif "Assign" == self.CTX():
            self.dbg("end INIT/Assign block")
            self.CTX("Job")

        else:
            raise TrAlfParseError('reached statement-block end in unexpected %s context, line %d' % (self.CTX(), self.linenum))

        if 0 == curTask['tid']:
            self.CTX("Job")

        # Can be more params for the enclosing Task after the block
        return self.addTaskParams(curTask)


    ## ===== ##


    def CTX(self, newctx=None):
        '''query or set the parsing context'''
        x = self.context
        if newctx:
            self.context = newctx
        return x

    def log(self, *a, **k):
        print(*a, file=sys.stderr)

    def dbg(self, *a, **k):
        if self.options.loglevel >= 5:
            ctxs = "(%s)," % self.context
            print("line %d %-5s  " % (self.linenum, ctxs), *a, file=sys.stderr)

    def trace(self, *a, **k):
        if self.options.loglevel >= 11:
            self.dbg(*a)

    def contextOK(self, pkey, jobdict):
        '''Confirm that the job directive 'pkey' is allowed
           within the current parsing context.'''

        if self.CTX() == "Expand":
            # Obscure compatibility issue:  alfred allowed expand output to
            # benignly begin with "Job" where the job node itself was ignored.
            # We try to emulate this weird aberration since it is still used
            # at a venerable studio. Let's call it: strongly deprecated.
            if pkey == "Job":
                self.CTX(pkey)
            elif pkey == "Task":
                self.CTX(pkey)
                self.taskStack = [jobdict]

        return pkey == self.CTX() or (
            self.CTX() == "Cmd" and pkey in (
                    "RemoteCmd",
                    "Cmd",
                )
            )


    def normalizeExeFilename(self, cmd):
        # Canonicalize path separators in argv[0] to always be
        # fwd slash '/' which works equally well on all platforms.
        #
        # Also Tractor assumes that the "base executable name"
        # will always be included as a limit tag, so extract that
        # while the pathlib machinery is spun up.
        a0 = cmd['argv'][0]

        # in python3 we could use the somewhat overwraught pathlib,
        # (but not portable to 2.x), for example:
        # if '\\' in a0:
        #   a0 = pathlib.PureWindowsPath(a0)
        #   cmd['argv'][0] = a0.as_posix()  # canonical with /
        #   cmdstem = a0.stem
        # else:
        #     cmdstem = pathlib.PurePosixPath(a0).stem

        # py2 approximation ...
        if '\\' in a0:
            a0 = a0.replace('\\', '/')
            cmd['argv'][0] = a0 # now tractor normalized
        b = os.path.basename(a0)
        cmdstem = os.path.splitext(b)[0]

        return cmdstem


    def chkIsList(self, txt):
        if not txt:
            return []
        elif list != type(txt):
            return self.tclListToPythonList(str(txt))
        else:
            return txt

    def chkDelayTime(self, timestr):
        ''' expect: float epoch secs, or "10/29 15:45"
            return: epoch secs
        '''
        if not timestr:
            return 0  # job can run now
        try:
            t = float(timestr)
            return t  # assumed secs since epoch like `date +%s`
        except:
            timestr = str(timestr)
            # save current time, and year
            now = time.time()  # current epoch secs
            nowtm = time.localtime(now) # default
            t = None
            # try several patterns, take the first that matches
            for pat in ("%m/%d %H:%M", "%m/%d/%y %H:%M",
                        "%m %d %H:%M", "%Y-%m-%d %H:%M"):
                try:
                    t = time.strptime(timestr, pat)
                    t = list(t)  # now mutable
                    break # success! parsed into struct_time
                except:
                    pass

            # Note: if we end up needing to modify the result
            # struct_time is an immutable tuple, make an editable list

            if not t:
                # try a parse with just hr:min 
                # if that succeeds, fill in the yr, mo, day from "now"
                try:
                    t = time.strptime(timestr, "%H:%M")
                    # success (no exception)
                    t = list(t)  # now mutable
                    t[0] = nowtm.tm_year
                    t[1] = nowtm.tm_mon
                    t[2] = nowtm.tm_mday
                    epsecs = time.mktime(t)
                    if epsecs < now - (60 * 60):
                        # given time would be more than 1hr ago
                        # so assume tomorrow
                        t[2] = nowtm.tm_mday + 1
                except:
                    print("Warning: aftertime can't be parsed '%s'" % timestr, file=sys.stderr)
                    return 0  # job can run now

            if t[0] == 1900:
                # python default 1900 when no yr specified (diff from libc)
                # so add the current year
                t = list(t)  # now mutable
                t[0] = nowtm.tm_year  # this year
                epsecs = time.mktime(t)
                if epsecs < now - (60 * 60 * 24 * 31 * 6):
                    # using this year the date would be more than 6mo
                    # in the past, so instead assume next year
                    t[0] = nowtm.tm_year + 1
                    epsecs = time.mktime(t)

            epsecs = time.mktime(t) # epoch secs

            return 0 if now == epsecs else epsecs


    def updateSlotCounts(self, node):
        '''Old alfscript syntax is -atleast -atmost
           but we prefer the more descriptive minslots maxslots.
           Port the old fmt to the new if it was used.
        '''
        if "atleast" in node:
            if "minslots" not in node:
                node["minslots"] = node["atleast"]
            del node["atleast"]
        if "atmost" in node:
            if "maxslots" not in node:
                node["maxslots"] = node["atmost"]
            del node["atmost"]

        if "samehost" in node:
            # Tractor(3) doesn't support old netrender style
            # allocation of multiple HOSTS to a single Cmd.
            # (Some other netrender thing may come along.)
            # So "samehost" is implicit in all Cmd/RemoteCmd.
            del node["samehost"]


    def reformatLimitTags(self, tagstr):
        '''Convert tcl list of limit tags to a simplified
           blank delimited list of names in a string.'''
        # The complete list of limit tags to tally will be:
        #   o  the app name (command executable), e.g. "txmake"
        #   o  plus the "-tags" list from the Cmd args
        #   o  plus the "-tags" list from the Job args
        #   o  plus the service keys that matched the blade
        #
        # The engine will add the cmdname and svckeys if
        # they are not already present in the cmd -tags list,
        # so that each limit tag is only tallied once. 
        # Make sure that the tag list for this current
        # context internally only has unique values.
        #
        # Job scripts may specify a list of tags using Tcl list notation:
        #     Cmd -tags {{houdiniengine_limit} {mpcpython}} ...
        #
        # The outbound json tag "lists" are not actual json/python lists,
        # due to dynamic composition requirements with other tag lists
        # (listed above). Instead they are sent as blank-delimited
        # words in a simple string. Tag names containing spaces are
        # not supported.

        # Use a python 'set' to uniquify the tag names,
        # then convert that back to a blank-delimited string.
        taglist = self.tclListToPythonList(tagstr)
        uniqueTags = set(taglist)
        return  ' '.join(uniqueTags).lower()


    def reformatDirmaps(self, tclMaps):
        '''Generate python list-of-lists from the tcl dirmap lists.
           Like: Job -dirmaps { {{from} {to} {zone}} {"from" to zone} }
        '''
        # Note: the job template type for dirmaps is 'str' so that the
        # whole complex nested block is read at once, but the outbound
        # result is expected to be a true json list of [list mappings],
        # so this subparsing step is also a type conversion.
        # First step is list of the separate maps:
        #   like { {a "b1 b2" c} {d e f} } -> ["a \"b1 b2\" c", "d e f"]
        # then subparse to get final list of lists
        #    -> [["a", "b1 b2", "c"], ["d", "e", "f"]]

        try:
            pyMaps = self.tclListToPythonList(tclMaps)
            if pyMaps:
                # then subparse the tcl list in each mapping
                stmp = StringIO()  # a reusable StringIO
                pyMaps = [self.tclListToPythonList(x, stmp) for x in pyMaps]
        except:
            raise TrAlfParseError("malformed directory mapping: '%s'" % tclMaps)
                    
        self.dbg("dirmaps:", pyMaps)
        if not pyMaps:
            pyMaps = ''  # match the template so it is skipped
        return pyMaps


    def handleOldWhenCmd(self, when, cmdstr, jobDict):
        '''Deal with -whendone and -whenerror options, which were an older
           approach to postscripts - just raw shell cmdlines. Convert to
           Cmds like those from the postscript block (eg. only attached to
           the commands list at the job level. In Alfred these were always
           local "shell-out" cmds, running on the artist's workstation via
           the local dispatcher. Tractor can do the same thing if (every)
           artist has a blade agent running on their workstation. OR if
           these cmdlines can be run anywhere on the farm then they can be
           RemoteCmds - but a service key is required to target the correct
           blades, see the tractor-spool --remotecleankey=ssss option.
        '''

        # Note: This is a highly simplified version of handleCmdStatement
        # for this special case. See that method for details and rationale.
        cmd = self.mkNewCmd()
        svc = self.options.cleanupSvc  # was a "cleaning service" given?
        if svc and svc != "local":
            cmd['service'] = svc
            cmd["type"] = 'R' # RemoteCmd
        else:
            cmd["type"] = 'L' # local Cmd

        # whendone/error are always postscript 'P' commands
        cmd["type"] += 'PE' if when=="whenerror" else 'PD'
        cmd["tags"] = when
        cmd["argv"] = ["TractorBuiltIn", "System", cmdstr] # shell out
        self.addCmdToTask(cmd, jobDict)


    def finalizeJobForJSON(self, jobDict):
        '''Check final job validity and wrap up some
           job format compatibility items.
        '''

        stlen = len(self.taskStack)

        if self.options.expandctx and stlen == 1 and \
            self.taskStack[0]["tid"] == 0:
                # job may have been pushed artificially for expand tasks
                self.taskStack = []
                stlen = 0

        if 0 != stlen:
            # still open subtask blocks
            raise TrAlfParseError("premature end of job file at line %d (task depth %d)" % (self.linenum,stlen))
        elif self.ncid < 1:
            # job with no cmds is weird/pointless but technically legal
            print("Warning: NO commands to launch specified in job", file=sys.stderr)

        self.CTX("JobEnd")

        self.updateSlotCounts(jobDict)

        # handle old compatibility translation:
        # prefer explicit "-priority N" to pbias, and remove pbias so it
        # isn't emitted. Since T2 pbias is no longer a "bias" but just
        # a priority value.
        pbias = None if "pbias" not in jobDict else jobDict.pop('pbias')
        if "priority" not in jobDict:
            jobDict["priority"] = 1.0 if pbias==None else pbias

        # Apply command-line option overrides to various values that 
        # may or may not have been set in the job script itself.
        ufile = getattr(self.options, "userfile", None)
        if ufile:
            # name of the file submitted by the user, on their client host,
            # rather than the name of tmp file on the engine host
            jobDict['spoolfile'] = ufile

        # And finally, renest the top-level items if necessary.
        if self.options.expandctx:
            # expand scripts only specify new tasks (not jobs)
            jobDict = jobDict.pop('subtasks')

        elif self.options.jsonAPI == "2.0":
            # re-nest topmost level as expected for 2.0
            jobDict = {
                "data": jobDict,
                "children": jobDict.pop('subtasks'),
            }

        return jobDict


    def generateJSON(self, jobDict):
        '''Translate the job python dict hierarchy to JSON.'''

        jobJSON = json.dumps(jobDict, indent=self.options.jsonformat[0],
                                      separators=self.options.jsonformat[1])

        del jobDict  # discard potentially large python dict repr

        self.dbg("parse complete!\n\n======\n")

        if not jobJSON:
            jobJSON = "{}"

        if self.options.jsonAPI == "2.0" and jobJSON[0]=='{':
            # Add expected 2.0 job "header" (specific opening dict lines),
            # basically replacing the opening brace ... and in python
            # that means generating an entire 2nd copy of the potentially
            # huge json job text that was just created.
            header = '{ "TractorJob": "2.0",\n' + \
                     '  "generator": "Tractor3 alf2json.py",\n'
            jobJSON = header + jobJSON[1:]  # replace opening json brace with header

        # done!
        return jobJSON


    ## ===== ##

    def rewind1(self, msg):
        '''Back up one character from the current read position.'''
        pos = self.linebuf.tell()
        self.dbg("rewind1 from", pos, msg)
        if pos > 0:
            self.linebuf.seek(pos-1, 0)


    def refillLineBuffer(self, withinQuote=False):
        '''Read input lines into the buffer used for parsing.
           The line-buffer (linebuf) will always represent one
           logical input (tcl) line, possibly constructed from
           several text lines with escaped continuations at the
           end. End of line represents end of expression in Tcl,
           as does semi-colon. Newlines and semicolons are allowed
           within quotes, so when a quoted string is being scanned
           more lines may need to be loaded from the source.
        '''

        # io.StringIO wrappers are used to represent each line so
        # that s.read(1) can be used uniformly on job scripts in
        # disk files or as in-memory string blocks. The wrappers
        # also avoid the problem of having to constantly check for
        # end-of-buffer when indexing if raw strings are used.
        # A single StringIO object is reused via truncate() and
        # write() of each new line.

        if not self.isAtLineBufferEnd():
            return True

        # set buffer back to empty.
        self.linebuf.seek(0, 0)
        self.linebuf.truncate(0)

        linechunk = ""

        while True:
            line = self.jobsrc.readline()
            if not line:
                # end of file
                return False

            self.linenum += 1
            line = line.strip()  # deemed ok losing whitespace ends in quotes
            self.dbg("next line:\n>>>> ", line)

            if not line:
                # skip empty lines
                continue

            if line[-1] == '\\':
                # continuation char, store chunk, read next line
                linechunk += line[:-1] + ' '
                continue

            # attach new line to last chunk, if any
            line = linechunk + line
            linechunk = ''

            if not withinQuote and line[0] == '#':
                # skip trivial case of lines that start with comments
                continue

            # line buffer now has one line of text to process
            self.linebuf.write(unicode(line))
            self.linebuf.seek(0, 0)
            break

        return True


    def tclListToPythonList(self, tcltxt, tmpio=None):
        '''Parse a tcl list like {a {b c} "d e f" g} into
           a python list like ["a", "b c", "d e f", "g"]
           (for later serialization into JSON).
        '''
        if tmpio:
            self.dbg("list tmpio is", type(tmpio))
            # caller has a temporary StringIO for reuse
            tmpio.seek(0, 0)
            tmpio.truncate(0)
            tmpio.write(tcltxt)
            tmpio.seek(0, 0)
            vsrc = tmpio
        else:
            vsrc = StringIO(unicode(tcltxt))

        vlist = []
        while True:
            item = self.findOneTclToken(altsrc=vsrc)
            if item == None:  # empty string '' is ok
                break
            else:
                vlist.append(item)

        return vlist


    def isAtLineBufferEnd(self, iobuf=None):
        '''Check if the current read position of the given StringIO
           buffer is at the end position, i.e. next read() would get ''.
        '''
        if not iobuf:
            iobuf = self.linebuf

        k = iobuf.tell()
        q = iobuf.seek(0,2)
        if k == q:
            # read pos is at the end
            return True
        else:
            # put the read position back where it was
            iobuf.seek(k, 0)
            return False

    def getchar(self, quoted=False, altbuf=None, skipSpace=False):
        '''Return one character from the script source.
           Skip comments and whitespace.

           Since Tcl allows string literals to contain newlines
           (as whitespace) this scan can't be purely line-based,
           and instead must resort to char-by-char to track nested
           Tcl strings - which occur a lot in Tractor/Alfred jobs.
           The underlying python io routines are likely using an
           internal cache already, but an app level one is created
           here to track line numbers for error messages, and to
           allow python built-in string methods to efficiently 
           handle other aspects which /are/ line-oriented in Tcl/Alf.
        '''

        if altbuf:
            # such as when creating a python list from a Tcl quoted list
            # (as an extension we allow comma as whitespace list delimiter)
            while True:
                c = altbuf.read(1)
                self.trace("getq" if quoted else "getc", str(c))
                if not c:
                    return ''
                if not quoted and skipSpace and (c.isspace() or c==','):
                    continue
                elif '\\' == c:
                    c += altbuf.read(1)
                    self.trace("get2", str(c))
                return c

        # otherwise it's the more complicated full job script scenario

        while True:
            # a single call to getchar may end up reading 
            # multiple no-op lines from the job

            c = self.linebuf.read(1)
            self.trace("getq" if quoted else "getc", str(c))

            if quoted and not c:
                # Reached end of line buffer, but if we're inside
                # a quoted multi-line string, refill another line,
                # and continue scanning.
                self.dbg("REFILL IN QUOTE", quoted)
                if self.refillLineBuffer(quoted):
                    # newline on current line was removed by strip()
                    # so return one of those, and let the caller call
                    # back again to get the first char of the new buffer.
                    return '\n'
                else:
                    return None   # got End Of File (EOF)

            if not quoted:
                if not c:
                    self.dbg("getch EOL1:", self.CTX())
                    return ''  # eol
                elif skipSpace and (c.isspace() or c==','):
                    # as an extension allow comma as list-delim whitespace
                    continue
                elif c == '#':
                    # comment, ends expr, skip to eol
                    self.dbg("getch COMMENT", self.CTX())
                    self.linebuf.seek(0, 2)
                    return ''
                elif c == ';':
                    # Tcl semi-colon is end of expr,
                    # but retain the buffer for next pass
                    self.dbg("getch eox")
                    return ''

            if '\\' == c:
                # advance and add escaped char like \"
                # incl backslash in quoted string values
                c = self.linebuf.read(1)
                self.trace("got2 \\"+c)
                if not c:
                    # Backlash at end of buffer. It's not a line-continuation
                    # since that would have been handled by refillLineBuffer.
                    c = '\n' if quoted else ''
                if quoted:
                    # note, returning 2 chars
                    c = "\\"+c

            return c


    def findOneTclToken(self, expectBlock=False, altsrc=None):
        '''Find a single (string) token using Tcl-like parsing rules.
           Several job-specific multi-expr blocks get special start/stop
           handling in this line-oriented job parser.

           If the "altsrc" is given, assume it is an alternative
           simple substring requiring further parsing e.g. a tcl list,
           not the more of the  mainline job script itself.
        '''

        # outside quotes, skip whitespace, find first non-space
        # (within this same line/expression)
        c1 = self.getchar(altbuf=altsrc, skipSpace=True)
        if not c1:
            return None  # eol/expr
        self.trace("f1%sstart %s" % ('x' if expectBlock else '', c1))

        if expectBlock:
            # Handle start of nested multi-expr block, send caller a
            # special "block begin" token, assume they'll switch context.
            #
            # Note: The old job handler just relied on Tcl to collect
            # the -subtasks and -cmds blocks as simple (multi-line)
            # quoted strings in braces. Then later those string-blocks
            # were recursively parsed in context. Here the blocks are
            # actively expected (in-line) in certain parameter contexts
            # and handled in-line by changing the "parsing context".
            # This approach creates a subtlety where block-begin is
            # effectively end-of-expression and remaining whitespace
            # in the active line buffer must be flushed.
            if c1 == '{':
                self.dbg("found block open")
                return "_BlockBegin_" # special parameter VALUE
            else:
                raise TrAlfParseError("expected start of nested sub-exprs, but got:", c1)

        value = ''
        qquote = None

        # collect the next "word"
        if c1 == '}':
            # reached end of a block
            self.dbg("got BLOCK END")
            return "_BlockEnd_"
        elif c1 == '"':
            # begin "evaluated" regular Tcl double-quoted string
            # \k escaped chars become single char k (typically only \")
            # "a\"b" is three chars
            # { has no special meaning, doesn't need to be balanced
            self.trace("begin dblq")
            qquote = '"' # the end quote to find
        elif c1 == '{':
            # begin "literal" regular Tcl brace-quoted string
            # " has no special meaning
            # \ is just a regular character
            # {a\"b} is four chars
            # Any internal { must have a matching }, as does the outer str.
            # Except {a\{b} and {a\}b} do not require balancing, as if they
            # were escaped, but length of those two examples is 4 chars(!?)
            self.trace("begin outbrace")
            qquote = '}' # the end quote to find
        else:
            value = c1  # first letter of token

        # qstack tracks beginning of " or { string, popped when ended
        # also tracks internal {} pairs when they need to be balanced
        qstack = [] if not qquote else [qquote]

        while True:
            cc = self.getchar(qquote, altbuf=altsrc)
            if not cc:
                # eol or eox or eof, return what we've collected
                break

            if qquote == cc:
                # found end of a quoted (sub)string
                # NOTE: valid for quoted string to be empty! "" or {}
                if cc == '}' and len(qstack) > 1:
                    # interior quote balanced  {say {hello, world} ok}
                    value += cc
                    qstack.pop()
                    qquote = qstack[-1]
                    self.trace("end brace, pop, stk=%s" % qstack)
                    continue
                else:
                    # outermost scope ended, string complete
                    self.trace("end %s str" % qquote)
                    qquote = None
                    qstack = []
                    break

            elif cc == '{' and '}' == qquote:
                # start new interior literal {} that needs to be balanced
                # {{hi there} "I'm a tcl" list} and string
                qquote = '}'
                qstack.append(qquote)
                self.trace("push new brace substr, stk=" % qstack)
                value += cc

            elif not qquote and cc == '}':
                self.rewind1("f1eot")
                break
            elif not qquote and (cc.isspace() or cc in ',;'):
                # Whitespace outside quotes marks end of token.
                # As an extension we allow comma as list delimiter.
                # Semi-colon is a Tcl expression delimiter, like newline
                # (when not in quotes). But need to call out "eol" without
                # actually incrementing line count.
                self.trace("f1eox: '%s'" % cc)
                break
            elif 2==len(cc) and cc[0]=='\\' and qquote != '}':
                # retain only the inbound escaped char in dbl-quoted str,
                # may be re-escape in json output
                # and handle weird \{ and \} inside {} cases
                # (otherwise retain both chars inside braces)
                self.trace("add escaped '%s'" % cc[1])
                value += cc[1]
            else:
                # otherwise it's just the next character in the string
                # (or retained \k inside {})
                value += cc

        if qquote:
            self.dbg("qstk:", qstack, "v:", value)
            raise TrAlfParseError("unterminated quoted string, line %d" % self.linenum)
        else:
            self.dbg("token '%s'" % value)
            return value


    def gatherNextParamPair(self, implicitKey=None):
        '''Collect a key-value pair for a Task or Command.
           These pairs are of the form:  -key_name value_string with
           only a couple exceptions determined by context. Values are
           strings when parsed, but will be converted to the type of
           the corresponding (default) item in the s_defaultParams table.
           Some key_names have values that are multi-item/line blocks.
           '''

        # Collect the -KEY-
        # capture the key word, like: -service
        # name only, not a fully general string token, no quotes etc
        #
        self.dbg("enter gatherParam")
        key = self.findOneTclToken()
        value = None

        if not key:
            # end of params for this task/cmd
            return (None, None)
        elif key == "_BlockEnd_":
            return (key, -1)
        elif len(key) > 1 and '-' == key[0]:
            key = key[1:] # skip hyphen
        elif implicitKey:
            # non-keyword allowed if standalone value is possible
            # e.g. Cmd argv or Task title
            self.dbg("using implicit key:", implicitKey)
            # so the token we DID gather is the VALUE for the implicit key
            value = key
            key = implicitKey
        else:
            raise TrAlfParseError("expected %s parameter name (-xxxx) but got '%s' on line %d" % (self.CTX(), str(key), self.linenum))

        pkeys = s_defaultParams[self.CTX()]
        if key not in pkeys:
            err = "unknown %s parameter '%s' - line %d" % (self.CTX(), key, self.linenum)
            if self.options.strict:
                raise TrAlfParseError(err)
            else:
                self.log("WARNING: " + err + " (ignored)")
                defaultValue = ''
                useValue = False
        else:
            defaultValue = pkeys[key]
            useValue = True

        vtype = type(defaultValue)

        # Some param keys are known to introduce LISTS of (simple) strings,
        # and some introduce BLOCKS of nested job expressions.
        # In the tcl parser the blocks were just long mulit-line strings,
        # and those blocks were eventually passed through the parser
        # recursively to handle sub objects. Instead, this implementation
        # will shift parsing "contexts" at the start of a block and process
        # the next expressions in-line immediately.
        hasBlock = key in ("subtasks", "cmds", "init", "cleanup", "postscript")

        # Collect the -VALUE-
        if value == None:
            value = self.findOneTclToken(hasBlock and useValue)
        if value == None:
            # note: /None/ indicates missing value token, but empty string ok
            err = "no value given for %s option '%s' on line %d" % (self.CTX(), key, self.linenum)
            if self.options.strict:
                raise TrAlfParseError(err)
            else:
                self.log("WARNING: " + err)
                return key, None  # skipped

        self.dbg("gatherNextParam got: k=<%s>  v=<%s>" % (str(key),str(value)))

        if not useValue:
            return key, None
        elif value == "_BlockBegin_":
            return key, value

        # The key name is now known to be valid.
        # Now confirm/convert string tokens to expected types.
        try:
            if vtype == int:
                value = int(value)

            elif vtype == float:
                value = float(value)

            elif vtype == list:
                # Recursively tokenize the string into a list.
                # This is not just python val.split() since the
                # string can contain Tcl-style string groups that
                # need to be retained as a single list element.
                # like argv of "grep -i {we hold these} decl.txt"

                self.dbg("reparse as list:", key, "from <%s>" % value)
                value = self.tclListToPythonList(value)

                if key == "retryrc":  
                    # special case of a list that is expected to be ints
                    value = [int(v) for v in value]

                self.dbg("     >", key, repr(value))

            # otherwise string is expected

            if key == "dirmaps":
                # This double-nested tcl string needs to be converted
                # into a python list of lists.
                value = self.reformatDirmaps(value.strip())

        except ValueError:
            raise TrAlfParseError("invalid value for '-%s' - requires %s, line %d" % (key, str(vtype), self.linenum))

        # Done finding one parameter key-value pair.
        # ... but only keep parameters that are different from the defaults.
        if value == defaultValue:
            value = None
            self.dbg("  skip default [%s]" % (key))
        else:
            self.dbg("         using '%s': %s" % (key, repr(value)))

        return key, value


    def addTaskParams(self, curTask):
        '''Loop over the input stream adding "-name value" pairs
           from the job script to the current Task's dict.
           If the name opens a sub-block, then stop here,
           change the parsing context, and let the caller's
           outer loop deal with the block context.
        '''

        self.dbg("enter addTaskP")
        # Compatibility issue, older job scripts allowed this:
        #   Task {my task title} -cmds {...}
        # where the Task title string VALUE is the next token
        # without a preceding '-title'. Some scripts /will/ 
        # provide the -title keyword, so we need to handle both
        # the explicit and implicit -title cases.
        taskImplicit = None if curTask.get('title') else "title"

        while True:
            self.dbg("addT loop ...")
            key, value = self.gatherNextParamPair(taskImplicit)
            self.dbg("   addT, key:", repr(key))
            if not key:
                # reached EOL, task parameters complete
                self.dbg("reached eol - emtpy key - after gather in addT")
                break
            elif not value:
                # skip, param has default value
                continue
            elif key == "_BlockEnd_":
                # End of parsing inside a subtask block.
                # Push that back for the top-level scanner.
                self.dbg("push-block-end in addTaskP")
                self.rewind1("taskblk")
                return curTask
            elif key == "subtasks":
                if value != "_BlockBegin_":
                    raise TrAlfParseError('no Task block for -subtasks, line %d' % self.linenum)
                self.dbg("taskStack PUSH - open subtask block in task", curTask['tid'])
                self.CTX("Task")
                self.taskStack.append(curTask) # push parent on the stack
                curTask = None
                break # new block temporarily shifts parsing to contents

            elif key == "init":
                # Job -init {Assign x y; ...}
                if value != "_BlockBegin_":
                    raise TrAlfParseError('no Assign block for -init, line %d' % self.linenum)
                self.dbg("start <<init>> block")
                self.CTX("Assign")
                break  # skip out to process (ignore) Assign statements

            elif key in ("cmds", "cleanup", "postscript"):
                if value != "_BlockBegin_":
                    raise TrAlfParseError('no Cmd block for -%s, line %d' % (key, self.linenum))

                # Parsing resumes with the new block,
                # allowing only RemoteCmd/Cmd,
                # and populating the commands list of the current task.
                #
                # Note that most inbound alfscript parameter names just end
                # up directly as keys in the outbound JSON dict, however the 
                # inbound alfscript -cmds list is renamed "commands" in JSON.
                # The "key" variable here could be set to "commands" for 
                # completeness, but it isn't actually referenced past this
                # point, the Cmd operator processing just populates the
                # outbound "commands" dict entry directly.

                self.cmdScope = {"cmds": 'C', "cleanup": 'D', "postscript": 'P'}[key]
                self.CTX("Cmd")
                break

            else:
                # We now have a complete key-value pair, and the
                # key is a valid item in the canonical Task dict,
                # and the value is different than the default.

                if key in ("whendone", "whenerror"):
                    # this old-school key-value gets converted to a Cmd,
                    # and don't add them to the task dict as k,v
                    self.handleOldWhenCmd(key, value.strip(), curTask)
                    continue
                elif key == "tags":
                    value = self.reformatLimitTags(value)
                elif key == 'title':
                    value = value.strip()

                # for job params, retain values that came from cmdline args,
                # those are treated as overrides to anything in the file
                if self.chkNoJobOverride(curTask, key):
                    # no override, add this key-value pair!
                    curTask[key] = value
                    self.dbg("  Adding", key, '=', value, "to task", curTask['tid'])

                if key == taskImplicit:
                    # found a value for the implicit key, so return
                    # to requiring proper key-value pairs only
                    taskImplicit = None

        # Reached end of line or beginning of new block
        if curTask and value != "_BlockBegin_":
            # Not opening a sub block, so this task is complete.
            self.dbg("END of param scan, tid", curTask['tid'])
            self.chkAttachTaskToParent(curTask)

            # further jobfile line parsing cannot append to that task anymore
            curTask = None

        return curTask

    def chkNoJobOverride(self, jdict, jkey):
        # Check whether the job received a value for this key
        # from command-line options that should be retained.
        # returns:
        # False: don't use new value from file, override was given
        # True: ok to use, no override
        return "Job" != self.CTX() or jkey not in jdict or \
            s_defaultParams["Job"][jkey] == jdict[jkey]

    def chkAttachTaskToParent(self, aTask):
        # This function may be called twice on a given task:
        # - once when the end of task params are definitively found
        # - maybe again if a task block is closed with the last task 
        #   not yet 'terminated' by definitive eol
        if not aTask:
            return
        tid = aTask.get('tid', None)
        self.dbg("chkAtt t:", tid)
        if tid and tid < 0:
            # Negative tid value indicates that this task
            # has not yet been attached to the job graph.
            # Now that all attributes are present it can
            # be attached. Negate the tid (to positive)
            # to indicate that it's already been attached.
            tid = -tid
            aTask['tid'] = tid

            self.updateSlotCounts(aTask)

            # shuffle into "2.0" format if reqd
            if self.options.jsonAPI == "2.0":
                aTask = {
                    "#": 'T'+str(tid),
                    "data": aTask,
                    "children": aTask.pop('subtasks')
                }

            pt = self.taskStack[-1] # parent on stack
            self.dbg("ADDING task", tid, "to task", pt['tid'])
            pt["subtasks"].append(aTask)
            self.dbg("      ... now nt =", len(pt["subtasks"]))


## === end class AlfJobParser ==== ##


if __name__ == "__main__":
    '''The alf2json module is imported into either tractor-spool or
       dbJobStaging inside the database.  This main() is used only
       for standalone testing.
    '''

    argc = len(sys.argv)
    jobfile = None

    class OptionHolder(object):
        pass
    opts = OptionHolder()
    opts.IsModuleTest = True
    opts.jobfile = None
    opts.jsonAPI = "2.0"
    opts.loglevel = 1
    opts.priority = 1.0
    opts.strict = False

    i = 0
    while  i < argc-1:
        i += 1
        opt = sys.argv[i]
        if opt == "--debug":
            opts.loglevel = 5
        elif opt == "--trace":
            opts.loglevel = 11 
        elif opt == "--title":
            i += 1
            opts.jtitle = sys.argv[i]
        elif opt == "--strict":
            opts.strict = True
        elif opt == "--paused":
            opts.paused = True
        elif opt == "--pretty":
            opts.jsonformat = (2, (', ', ': '))
        elif opt == "--expand":
            opts.expandctx = "1.234.5.6.0.0"
        elif opt == "--3.0":
            opts.jobspec = "3.0"
        elif opt[0] == "-":
            print("unknown alf2json option:", opt, file=sys.stderr)
            break
        elif i == argc - 1:
            jobfile = opt
        else:
            print("only one job filename allowed, found:", sys.argv[i:], file=sys.stderr)
            break

    if not jobfile:
        usage()

    if not os.path.exists(jobfile):
        print("can't access job file: '%s'" % jobfile, file=sys.stderr)
        sys.exit(2)

    jobJSON = ParseAlfJob(opts, jobfile, None)
    if not jobJSON:
        sys.exit(113)

    sys.stdout.write(jobJSON)
    sys.stdout.write('\n')
    sys.stdout.flush()

