# Copyright (c) 1986-2024 Pixar. All rights reserved.
#
# The information in this file (the "Software") is provided for the exclusive
# use of the software licensees of Pixar ("Licensees").  Licensees have the
# right to incorporate the Software into other products for use by other
# authorized software licensees of Pixar, without fee. Except as expressly
# permitted herein, the Software may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior written
# permission of Pixar.
#
# The copyright notices in the Software and this entire statement, including the
# above license grant, this restriction and the following disclaimer, must be
# included in all copies of the Software, in whole or in part, and all permitted
# derivative works of the Software, unless such copies or derivative works are
# solely in the form of machine-executable object code generated by a source
# language processor.
#
# PIXAR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL PIXAR BE
# LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.  IN NO CASE WILL
# PIXAR'S TOTAL LIABILITY FOR ALL DAMAGES ARISING OUT OF OR IN CONNECTION WITH
# THE USE OR PERFORMANCE OF THIS SOFTWARE EXCEED $50.
#
# Pixar
# 1200 Park Ave
# Emeryville CA 94608


import sys, os, uuid, binascii, ctypes

if sys.platform == 'win32':
    try:
        try:
            import winreg
        except ImportError:
            import _winreg as winreg
    except ImportError:
        pass  # calls to winreg.xxx will throw; caught by caller

## ----------------------------------------------- ##
def GetHostUUID ():
    '''Attempt to find the OS-assigned UUID for this host'''

    #
    # In the case of virtual machines, several instances started from
    # the same VM image will likely share the "soft" OS values readable
    # by non-root users.  We might defer to some other well known unique
    # value, from the hyporvisor etc, in that case. For now we assume that
    # these hosts are being provisioned by Tractor itself, or by scripts
    # that can be made to follow Tractor conventions.  A provisioning
    # script usually includes a script run after boot. If the built-in
    # host uuid is not already unique to each instance, then we assume
    # that the provisioning script will create a unique value and write
    # it into /usr/local/tractor-blade.uuid on unix systems. We'll check
    # for that and use in preference to the OS value.
    #
    # For tractor-blade developer testing purposes we will also check
    # for an environment variable override.
    #

    hostUUID = os.getenv("TRACTOR_BLADE_UUID")

    if hostUUID is None:
        # try the Tractor override file
        try:
            with open("/usr/local/tractor-blade.uuid", "r") as f:
                for line in f:
                    line = line.strip()
                    if 0==len(line) or line.startswith("#"):
                        continue
                    else:
                        hostUUID = line.split()[0]
                        # now continue reading lines, we keep the last line
        except IOError:
            pass

    try:
        if hostUUID is not None:
            pass # otherwise check the OS values

        elif sys.platform == 'win32':
            vkey = winreg.OpenKeyEx(winreg.HKEY_LOCAL_MACHINE,
                                    "SOFTWARE\\Microsoft\\Cryptography")
            guid = winreg.QueryValueEx(vkey, "MachineGuid")
            winreg.CloseKey(vkey)
            hostUUID = str( guid[0] )

        elif sys.platform == 'darwin':
            osxlibc = ctypes.CDLL( ctypes.util.find_library("c") )
            class TIMESPEC(ctypes.Structure):
                _fields_ = [
                    ('tv_sec', ctypes.c_long),
                    ('tv_nsec', ctypes.c_long),
                ]
            tv = TIMESPEC()
            tv.tv_sec = 0
            tv.tv_nsec = 0
            uuidc = ctypes.create_string_buffer(16)
            rc = osxlibc.gethostuuid( uuidc, ctypes.byref(tv) )
            if 0 == rc:
                hostUUID = binascii.hexlify( uuidc.value )

        else:  # linux
            try:
                f = open("/etc/machine-id", 'r')  # RHEL7-like
                hostUUID = f.read()
                f.close()
            except IOError:
                try:
                    f = open("/var/lib/dbus/machine-id", 'r')  # RHEL5 & 6-like
                    hostUUID = f.read()
                    f.close()
                except IOError:
                    pass  # use the fallback

    except Exception:
        hostUUID = None  # reset, use fallback

    if not hostUUID:
        # hashed ether addr fallback
        hostUUID = str( uuid.uuid5(uuid.NAMESPACE_DNS, str(uuid.getnode())) )

    if str != type(hostUUID):
        hostUUID = hostUUID.decode('utf-8')

    return hostUUID.replace('-','').strip()

## ----------------------------------------------- ##

